<?php
$doc = new DOMDocument("1.0","UTF-8");
$doc->formatOutput=true;
$question = $doc->createElement('Question');
$doc->appendChild($question);
$ques = $doc-> createElement("Category");
$ques ->setAttribute("type","easy");
$question->appendChild($ques);
$desc = $doc -> createElement("Description","Highest mountain");
$ques->appendChild($desc);
$op1 = $doc->createElement("OptionA","MtEve");
$ques->appendchild($op1);
$op2=$doc->createElement("OptionB","K2");
$ques->appendChild($op2);
$op3=$doc->createElement("OptionC","Aple");
$ques->appendChild($op3);
$op4=$doc->createElement("OptionD","Kalsubai");
$ques->appendChild($op4);
$answer=$doc->createElement("Answer","MtEverest");
$ques->appendChild($answer);
$ques = $doc ->createElement("Category");
$ques->setAttribute("type","Hard");
$question->appendChild($ques);
$desc = $doc -> createElement("Description","Richest Man");
$ques->appendChild($desc);
$op1 = $doc->createElement("OptionA","Bezos");
$ques->appendchild($op1);
$op2=$doc->createElement("OptionB","Elonmusk");
$ques->appendChild($op2);
$op3=$doc->createElement("OptionC","Pranit");
$ques->appendChild($op3);
$op4=$doc->createElement("OptionD","Adani");
$ques->appendChild($op4);
$answer=$doc->createElement("Answer","Pranit");
$ques->appendChild($answer);
$ques= $doc->createElement("Category");
$ques->setAttribute("type","Medium");
$question->appendChild($ques);
$desc = $doc -> createElement("Description","Best Song");
$ques->appendChild($desc);
$op1 = $doc->createElement("OptionA","Ease off");
$ques->appendchild($op1);
$op2=$doc->createElement("OptionB","Easy on Me");
$ques->appendChild($op2);
$op3=$doc->createElement("OptionC","Monster");
$ques->appendChild($op3);
$op4=$doc->createElement("OptionD","1000 Miles");
$ques->appendChild($op4);
$answer=$doc->createElement("Answer","Monster");
$ques->appendChild($answer);
$doc->save("questionBank.xml");
echo"questionBank.xml created";

?>